config/routes.rb
Aplicacion::Application.routes.draw do
  devise_for :users

  resources :orders

  resources :line_items

  resources :carts

  get "vista/inicio"

  get "vista/empresa"

  get "vista/servicio"

  get "vista/producto"

  get "vista/contactar"

  get "vista/video"

  get "vista/status"

  get "vista/pagarorden"

  get "tienda/index"

  get "tienda/pagina"

  get "tienda/pagina2"

  get "tienda/vista"

  get "tienda/miscelaneus"

  get "tienda/vistaDetalle"

  resources :vista

  resources :productos do
    get :who_bought, on: :member
  end

  get 'admin' => 'admin#index'

  controller :sesion do
  get 'login' => :nueva
  post 'login' => :crear
  delete 'logout' => :borrar
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
    put 'increase1', on: :member
    put 'erase', on: :member
  end
  resources :usuarios

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users

  root to: 'vista#inicio', as: 'tienda'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def total_price
		line_items.to_a.sum {|item| item.total_price}
	end

	def add_producto(producto_id,quantity)
		current_item = line_items.find_by_producto_id(producto_id)
		if current_item
			current_item.quantity += quantity
		else
			current_item = line_items.build(producto_id: producto_id)
			current_item.quantity += quantity - 1
		end
			current_item
	end

	def decrease(line_item_id)
	    current_item = line_items.find(line_item_id)
	    if current_item.quantity > 1
	      current_item.quantity -= 1
	    else
	      current_item.destroy
	    end
	    current_item
	end

  def increase(line_item_id)
    current_item = line_items.find(line_item_id)
    current_item.quantity += 10
    current_item
  end

  def increase1(line_item_id)
    current_item = line_items.find(line_item_id)
    current_item.quantity += 1
    current_item
  end

  def erase(line_item_id)
	current_item = line_items.find(line_item_id)
	current_item.destroy
	current_item
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #skip_before_filter :authorize, only: [:create, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource :only => [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
      begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to tienda_url, notice: 'Carro Invalido'
      else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
      end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to tienda_url, notice: "Tu carro esta actualmente vacio" }
      format.js   
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2>Tu carro de compras</h2>
<table>
  <%= render(cart.line_items) %>
<tr class="total_line">
  <td colspan="2">I.V.A</td>
  <td class="IVA_cell"><%= number_to_currency(cart.total_price*12/100, :unit => "Bsf ") %></td>
</tr>
<tr class="total_line">
  <td colspan="2">Total</td>
  <td class="total_cell"><%= number_to_currency(cart.total_price + cart.total_price*12/100, :unit => "Bsf ") %></td>
</tr>
</table>  
<%= button_to 'Continuar con la compra', new_order_path, method: :get, :class => 'button1' %>
<%= button_to 'Vaciar carro', cart, method: :delete, remote: true , :class => 'button2'%>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$('#cart tr').not('.total_line').remove();
$('#cart').hide('blind', 500);

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
	<%= render @cart %>
	