config/routes.rb
Aplicacion::Application.routes.draw do
  devise_for :users

  resources :orders

  resources :line_items

  resources :carts

  get "vista/inicio"

  get "vista/empresa"

  get "vista/servicio"

  get "vista/producto"

  get "vista/contactar"

  get "vista/video"

  get "vista/status"

  get "vista/pagarorden"

  get "tienda/index"

  get "tienda/pagina"

  get "tienda/pagina2"

  get "tienda/vista"

  get "tienda/miscelaneus"

  get "tienda/vistaDetalle"

  resources :vista

  resources :productos do
    get :who_bought, on: :member
  end

  get 'admin' => 'admin#index'

  controller :sesion do
  get 'login' => :nueva
  post 'login' => :crear
  delete 'logout' => :borrar
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
    put 'increase1', on: :member
    put 'erase', on: :member
  end
  resources :usuarios

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users

  root to: 'vista#inicio', as: 'tienda'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item
	attr_accessible :nombre, :codigo, :marca, :cantidad, :precio, :imageurl, :modelo,:flag1
	
	attr_accessible :imagenagregada
    has_attached_file :imagenagregada, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "logo/no_dispo.jpg"
    validates_attachment :imagenagregada,
  	:content_type => { :content_type => /jpg|gif|png|jpeg/},
  	:size => { :in => 0..800.kilobytes }

  	MISCELANEUS = [ "no", "si" ]

	validates :nombre, :codigo, :marca, :cantidad, :precio, :modelo, :imageurl, presence: true
	validates :precio, numericality: {greater_than_or_equal_to: 0.01}
	validates :codigo, uniqueness: true
	validates :imageurl, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)$}i,
		message: 'La imagen debe tener extension JPG,GIF o PNG'
		}

	def self.search(search)  
	     if search  
	      where('nombre LIKE ? OR codigo LIKE ? OR marca LIKE ?',"%#{search.upcase}%","%#{search.upcase}%","%#{search.downcase.capitalize}%").limit(10)  
	    else
	      where('imageurl NOT LIKE ?', "logo%").order("RANDOM()").limit(6)
	    end  
  	end 


  	def self.vista(marca,nombre)
  		where('marca LIKE ? AND nombre LIKE ?',"#{marca}","#{nombre}%")
  	end

  	def self.marcas
  		 find_by_sql("select marca from productos group by marca")
  	end

  	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items presente')
			return false
		end
	end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  #before_filter :authorize
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Su productos fue creado correctamente' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Su producto ha sido actualizado' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @producto = Producto.find(params[:id])
      respond_to do |format|
        format.atom
    end 
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br />
    <%= f.text_field :imageurl %>
  </div>

  <div class="field">
    <%= f.label :image_Agregada %><br />
    <%= f.file_field :imagenagregada %>
  </div>
  
  <div class="field">
    <%= f.label :modelo %><br />
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :miscelaneus %><br />
    <%= f.select :flag1, Producto::MISCELANEUS, 
    prompt: 'Escoja miscelaneus si/no' %>
  </div>
  <div class="actions">
    <%= f.submit 'Actualizar producto' %>
  </div>
<% end %>

app/views/productos/_productos.html.erb
<table>
    <% @productos.each do |producto| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
            <% if !producto.imagenagregada.to_s.include?('no_dispo') %>
            <%= image_tag producto.imagenagregada.url , class: 'list_image' %>
            <% else %>
            <%= image_tag(producto.imageurl, class: 'list_image') %>
            <% end %>
        <td class="list_description">
            <dl>
            <dt><%= producto.nombre %></dt>
            <dd><%= producto.codigo %></dd>
            <dd><%= producto.precio %></dd>
            <dd><%= producto.marca %></dd>
            </dl>
        </td>
        <td class="list_actions">
            <%= link_to 'Mostrar', producto %><br/>
            <%= link_to 'Editar', edit_producto_path(producto) %><br/>
            <%= link_to 'Destruir', producto, confirm: 'Estas seguro?', method: :delete %>
        </td>
      </tr>
    <% end %>
</table>

app/views/productos/edit.html.erb
<h1>Editar las caracteristicas del Producto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Ir atras', productos_path %>

app/views/productos/index.html.erb
<h1>Lista de productos</h1>

<%= form_tag productos_path, :method => 'get', :id => "productos_search" do %>
    <h3>Busqueda de productos por Codigo</h3>
    <p style="font-style:italic;font-size:12px;font-color:gray;">
    	En este cambo escribiras el código de tu producto
    </p>    
    <p>  
    <%= text_field_tag :search, params[:search] %>  
    <%= submit_tag "Buscar", :nombre => nil %>  
    </p>  
    <% end %> 
    
<div id="productos"><%= render 'productos' %></div>

<br />

<%= link_to 'Nuevo producto', new_producto_path %>

app/views/productos/index.js.erb
$('#productos').html('<%= escape_javascript(render("productos")) %>'); 

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Ir atras', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @producto.nombre %>
</p>

<p>
  <b>Codigo:</b>
  <%= @producto.codigo %>
</p>

<p>
  <b>Marca:</b>
  <%= @producto.marca %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @producto.cantidad %>
</p>

<p>
  <b>Precio:</b>
  <%= @producto.precio %>
</p>

<p>
  <b>Imageurl:</b>
  <%= @producto.imageurl %>
</p>

<p>
  <b>Direccion de la imagen agregada:</b>
  <%= @producto.imagenagregada %>
</p>

<p>
  <b>Modelo:</b>
  <%= @producto.modelo %>
</p>


<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Ir atras', productos_path %>