config/routes.rb
Aplicacion::Application.routes.draw do
  devise_for :users

  resources :orders

  resources :line_items

  resources :carts

  get "vista/inicio"

  get "vista/empresa"

  get "vista/servicio"

  get "vista/producto"

  get "vista/contactar"

  get "vista/video"

  get "vista/status"

  get "vista/pagarorden"

  get "tienda/index"

  get "tienda/pagina"

  get "tienda/pagina2"

  get "tienda/vista"

  get "tienda/miscelaneus"

  get "tienda/vistaDetalle"

  resources :vista

  resources :productos do
    get :who_bought, on: :member
  end

  get 'admin' => 'admin#index'

  controller :sesion do
  get 'login' => :nueva
  post 'login' => :crear
  delete 'logout' => :borrar
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
    put 'increase1', on: :member
    put 'erase', on: :member
  end
  resources :usuarios

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users

  root to: 'vista#inicio', as: 'tienda'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :producto
	belongs_to :cart

	def total_price
		producto.precio * quantity
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  #skip_before_filter :authorize, only: [:create, :increase, :destroy, :decrease]
  before_filter :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource :only => [:erase,:create, :increase, :increase1, :destroy, :decrease]
  # GET /carts
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    producto = Producto.find(params[:producto_id])
    @quantity = params[:quantity].to_i
    @line_item = @cart.add_producto(producto.id,@quantity)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to tienda_url }
        format.js {@current_item = @line_item}
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
  # PUT /line_items/1
  # PUT /line_items/1.json
  def decrease
    @cart = current_cart
    @line_item = @cart.decrease(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to tienda_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def increase
    @cart = current_cart
    @line_item = @cart.increase(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to tienda_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

    # PUT /line_items/1
  # PUT /line_items/1.json
  def increase1
    @cart = current_cart
    @line_item = @cart.increase1(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to tienda_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def erase
    @cart = current_cart
    @line_item = @cart.erase(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to tienda_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto_id %><br />
    <%= f.number_field :producto_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
    <% end %>

 <% if @mailer %>
    <% @impuesto=((line_item.total_price.to_f)*12/100.to_f).round(2) %>
    <% @TotalItem=(line_item.total_price).round(2) %>
    <td><%= line_item.producto.codigo %></td>
    <td><%= line_item.producto.modelo %></td>
    <td><%= line_item.producto.nombre %></td>
    <td><%= line_item.quantity %></td>
    <td><%= line_item.producto.precio %></td>
    <td>12.0</td>
    <td><%= @impuesto %></td>
    <td><%= @TotalItem %></td>
    </tr>
<% else %>
    <td class="item_quantity"><%= line_item.quantity %>&times;</td>
    <td class="item_nombre"><%= line_item.producto.nombre %></td>
    <td class="item_price"><%= number_to_currency(line_item.total_price, :unit => "Bsf ")    %></td>
    <td><%= button_to "E", erase_line_item_path(line_item), :method => :put, remote: true, :class => 'erase' %></td>
    </tr>
<% end %>

app/views/line_items/create.js.erb
$("#notice").hide();
if ($('#cart tr').length == 1) 
{ $('#cart').show('blind', 1000); };

$('#cart').html("<%=j render @cart %>");

$('#current_item').css({'background-color':'#B9D3EE'}).
animate({'background-color': 'white'}, 700);

app/views/line_items/decrease.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'#B9D3EE'}).animate({'background-color':'white'}, 1000);
if ($('#cart tr').length==1) {
    // Hide the cart
    $('#cart').hide('blind', 1000);    
}

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/erase.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'#B9D3EE'}).animate({'background-color':'white'}, 1000);
if ($('#cart tr').length==1) {
    // Hide the cart
    $('#cart').hide('blind', 1000);    
}

app/views/line_items/increase.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'#B9D3EE'}).animate({'background-color':'white'}, 1000);

app/views/line_items/increase1.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'#B9D3EE'}).animate({'background-color':'white'}, 1000);

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Producto</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.producto_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Producto:</b>
  <%= @line_item.producto_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>