config/routes.rb
Aplicacion::Application.routes.draw do
  devise_for :users

  resources :orders

  resources :line_items

  resources :carts

  get "vista/inicio"

  get "vista/empresa"

  get "vista/servicio"

  get "vista/producto"

  get "vista/contactar"

  get "vista/video"

  get "vista/status"

  get "vista/pagarorden"

  get "tienda/index"

  get "tienda/pagina"

  get "tienda/pagina2"

  get "tienda/vista"

  get "tienda/miscelaneus"

  get "tienda/vistaDetalle"

  resources :vista

  resources :productos do
    get :who_bought, on: :member
  end

  get 'admin' => 'admin#index'

  controller :sesion do
  get 'login' => :nueva
  post 'login' => :crear
  delete 'logout' => :borrar
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
    put 'increase1', on: :member
    put 'erase', on: :member
  end
  resources :usuarios

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users

  root to: 'vista#inicio', as: 'tienda'

end

app/views/layouts/_googlemaps.html.erb
 <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
 <script>
      function initialize() {
        var map_canvas = document.getElementById('map_canvas');
        var map_options = {
          center: new google.maps.LatLng(10.480918,-66.911143),
          zoom: 18,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(map_canvas, map_options)
      }
      $(document).ready(function() { initialize(); });
      
    </script>
<div id = "map_canvas"></div>

app/views/layouts/_menu.html.erb
<ul id="menu">  
		<% if @productos1 %>
			<% @productos1.each do |producto| %>
			  <li id = "linkMenu">
			   <%= link_to "#{producto.marca}", tienda_pagina_path(:marca => "#{producto.marca.downcase}") %>
			  	<ul><% if "#{producto.marca}" == 'Copeland' %>
			  		<% @Busqueda = @productoCop %>
			  		<% elsif "#{producto.marca}" == 'Carrier' %>
			  		<% @Busqueda = @productoCarr %>
			  		<% elsif "#{producto.marca}" == 'Trane' %>
			  		<% @Busqueda = @productoTran %>
			  		<% elsif "#{producto.marca}" == 'Bitzer' %>
			  		<% @Busqueda = @productoBitzer %>
			  		<% else %>
			  		<% @Busqueda = @productoYork %>
			  		<% end %>
			  		<% @Busqueda.each do |producto1| %>
			  		<li id = "linkMenu2">
			  		<%= link_to "#{producto1.nombres.split(" ").first.downcase.capitalize}", tienda_pagina2_path(:marca => "#{producto.marca.downcase}", :nombre => "#{producto1.nombres}") %>
			  		</li>
			  		<% end %>
			  		<li id = "linkMenu2"><%= link_to "Miscelaneus", tienda_miscelaneus_path(:marca => "#{producto.marca.downcase}") %></li>
			  	</ul>
			  </li>	
			<% end %> 
		<% end %>        
</ul>

app/views/layouts/_servicio.html.erb
<div class= "default">
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/York.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "York")%></div>
</div>
<div class = "servicio2">
				<div class = "Proc1">
					<h2>Desarmado y evaluación</h2>
					<%= image_tag("PROCESO/desarmado.jpg", class: 'imgProc1')%>
					<p>Una vez desarmado el equipo, el supervisor de taller toma las piezas de los compresores y los equipos de medicion necesarios para llevar a cabo una evaluacion mecánica de cada una de las piezas<br>
					El bloque es también examinado con el fin de descartar fallas graves del mismo
					</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc2">
					<h2>Recepción de equipos</h2>
					<%= image_tag("PROCESO/recepcion.jpg", class: 'imgProc2')%>
					<p>El compresor ingresa a nuestra empresa donde es identificado por su procedencia, marca, modelo, fecha de ingreso y estado del equipo, con esto se define su ficha técnica que servira para mantener el control del equipo.
					</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc3">
					<h2>Rebobinado</h2>
					<%= image_tag("PROCESO/rebobinado.jpg", class: 'imgProc3')%>
					<p>Todo compresor que presente daños en el embobinado es enviado al área de rebobinado, donde el nucleo del motor es limpiado.</p>
					<h4>Limpieza del estator</h4>
					<p>En esta zona se despeja el stator del embobinado dañado, el stator es limpiado con técnica de sandblasting o chorro de arena, garantizando el arranque de todas las impurezas presentes</p>
					<h4>Rebobinado</h4>
					<p>Con los datos originales de fabricación, el motor es rebobinado, en copelancita de venezuela se rebobinan equipos con capacidad de hasta 100 HP, incluyendo unidades trifásicas bifásicas o monofásicas desde 120 hasta 240 voltios.</p>
					<h4>Varnizado</h4>
					<p>Con el fin de proteger y garantizar un rendimiento de los motores rebobinados, estos son varnizados y llevados altas temperaturas en nuestros hornos, de este modo se garantiza un recubrimiento optimo</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc4">
					<h2>Rectificacion</h2>
					<%= image_tag("PROCESO/rectificacion2.jpg", class: 'imgProc4')%>
					<p>Toda pieza que fuese encontrada fuera de medida, pasa al área de rectificación, las piezas que tipicamente son rectificadas, son el cigueñal, el bloque y los platos de válvulas.</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc5">
					<h2>Stock de respuesto</h2>
					<%= image_tag("PROCESO/stock.jpg", class: 'imgProc5')%>
					<p>En Copelancita de Venezuela contamos con un amplio Stock de respuestos, es asi como garantizamos a nuestros clientes la entrega de sus equipos de manera oportuna. <br> 
					Una vez que las partes y piezas están limpias y rectificadas, el almacen entrega las piezans necesarias para reemplazar aquellas que fueron diagnosticadas como dañadas.
					</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc6">
					<h2>Ensamblado</h2>
					<%= image_tag("PROCESO/ensamblado.jpg", class: 'imgProc6')%>
					<p>El proceso de armado se lleva a cabo una vez que se dispone de todas las piezas nuevas y rectificadas. El ensamblaje de nuestro equipos se hace siguiendo las más estrictas normas internas</p>
					<h4>Prueba en vacio</h4>	
					<p>Para verificar la calidad del proceso de ensamblaje y de reconstrucción del embobinado, nuestros equipos son puestos en marcha antes de instalar los cabezales de los mismos </p>
					<h4>Prezurizado</h4>	
					<p>Luego de haber verificado la calidad del ensamblaje, el equipo es pintado y presurizado con nitrogeno.</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc7">
					<h2>Despacho y/o almacenaje</h2>
					<%= image_tag("PROCESO/despacho2.jpg", class: 'imgProc7')%>
					<p>Una vez terminado el proceso de reparacion y reconstrucción del equipo, el cliente es informado para realizar el despacho del mismo, miestras este es guardado en el rack de compresores en la espera.</p>
					<button type="button" class="button">Esconder</button>
				</div>
				<div class = "Proc8">
					<h2>Evaluación de presupuesto</h2>
					<%= image_tag("PROCESO/presupuesto.jpg", class: 'imgProc8')%>
					<p>Una vez evaluada la ficha del compresor, esta pasa a las oficinas administrativas donde se realiza un presupuesto ajustado al daño que posea el equipo, incluyendole recontrucciones, rectificaciones y reemplazo de partes y piezas mecanicas y/o eléctricas <br> 
					Una vez realizado esto se notifica al cliente el estado de su equipo y el costo de la reconstruccion del mismo , con su aprobación continuamos el proceso.
					</p>
					<button type="button" class="button">Esconder</button>
				</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aplicacion</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>' id="body">
<div id="contenido">
	<div id="banner_2">
		<%= image_tag("logo/logo_C.png",class: 'logo')%>
		<%= image_tag("logo/nombre.png",class: 'nombre')%>
	</div>
	<div id="navegacion">
		<ul>
			<li><%= link_to "Inicio", tienda_url %></li>
			<li><%= link_to "Empresa", vista_empresa_path %></li>
			<li><%= link_to "Servicios", vista_servicio_path %></li>
			<li><%= link_to "Productos", tienda_index_path %></li>
			<li><%= link_to "Contacto", vista_contactar_path %></li>
			<% if user_signed_in? %>
			<li><%= link_to('Mis compras', vista_status_path) %></li> 
			<li><%= link_to('Como comprar', vista_video_path) %></li> 
  			<li><%= link_to('Salir', destroy_user_session_path, :method=>'delete') %></li>  
  			<%else%>
  			<li><%= link_to "Login", new_user_session_path %></li>
  			<li><%= link_to "Nuevo usuario?", new_user_registration_path %></li>
			<%end%>
		</ul>
	</div>	
<div id="side_1" class="inline">
		<%= render 'layouts/menu' %>
		<%= link_to image_tag("COMPRESORES/Copeland_logo_2.jpg",class: 'logoSide'), tienda_pagina_path(:marca => "Copeland") %>
		<%= link_to image_tag("COMPRESORES/Carrier_logo_2.jpg",class: 'logoSide'), tienda_pagina_path(:marca => "Carrier") %>
		<%= link_to image_tag("COMPRESORES/Bitzer_logo_2.jpg",class: 'logoSide'), tienda_pagina_path(:marca => "Bitzer") %>
		<%= link_to image_tag("COMPRESORES/York_logo.jpg",class: 'logoSide'), tienda_pagina_path(:marca => "York") %>
		<%= link_to image_tag("logo/logoSide2.gif",class: 'newProduct'), tienda_index_path %>	
</div>	
<div id="main" class="inline">
	<%= yield %>
</div>

	<div id="side" class="inline">
		<% if @cart %>
		<div id="cart">
			<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
			<%= render @cart %>
			<% end %>
		</div>
		<% elsif @identifiant == "vistaInicial" %>
			<div class= "default">
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
		<% elsif @identifiant == "vistaContacto" %>
			<div class= "default">
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
		<% elsif @identifiant == "servicio" %>
			<div class= "default">
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
			<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
		<% elsif @identifiant == "vistaEmpresa" %>
			<div class= "default">
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
		<% elsif @identifiant == "vistaStatus" %>
			<div class= "default">
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
			<% elsif @identifiant == "vistaVideo" %>
			<div class= "default">
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
			<% elsif @identifiant == "vistaPagar" %>
			<div class= "default">
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Carrier.jpg", class: 'imgComp1'), tienda_pagina_path(:marca => "Carrier") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Copeland.jpg", class: 'imgComp2'), tienda_pagina_path(:marca => "Copeland")%></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Trane.jpg", class: 'imgComp3'), tienda_pagina_path(:marca => "Trane") %></div>
				<div id = "imgCompresores"><%= link_to image_tag("COMPRESORES/Bitzer2.jpg", class: 'imgComp4'), tienda_pagina_path(:marca => "Bitzer")%></div>
			</div>
		<% end %>	
	<% if user_signed_in? and current_user.role_ids[0] == 3 %>
	<ul>
	<li>Bienvenido administrador!!</li>
	<li><%= link_to 'Ordenes', orders_path %></li>
	<li><%= link_to 'Productos', productos_path %></li>
	<li><%= link_to 'Usuarios', users_path %></li>
	</ul>
	<% end %>
</div>
	
	<div id="footer">
		<div id="links">
		<ul>
		<li><%= link_to "Inicio", tienda_url %></li>
		<li><%= link_to "Empresa", vista_empresa_path %></li>
		<li><%= link_to "Servicios", vista_servicio_path %></li>
		<li><%= link_to "Productos", tienda_index_path %></li>
		<% if user_signed_in? %>
  		<li><%= link_to('Salir', destroy_user_session_path, :method=>'delete') %></li>  
  			<%else%>
  		<li><%= link_to "Login", new_user_session_path %></li>
  		<li><%= link_to "Nuevo usuario?", new_user_registration_path %></li>
		<%end%>
	</ul>
	</div>
	<%= image_tag("logo/banner_3.jpg")%>

</div>	
</body>
</html>